apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deploy.yaml
  - mesh.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
labels:
  - pairs:
      app.kubernetes.io/name: rpc-server
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: arch
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
